name: Test, Build, and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  # ===============================================
  #  JOB 1: Run Tests
  # ===============================================
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install "poetry>=1.2.0"

      - name: Install project dependencies
        run: poetry install --no-root

      - name: Run pytest
        run: poetry run pytest

  # ===============================================
  #  JOB 2: Build and Deploy
  # ===============================================
  deploy:
    needs: test
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      
      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/task-reminder-api:${{ github.sha }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/task-reminder-api:${{ github.sha }}

      - name: Deploy Bicep template
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
          template: ./infra/main.bicep
          parameters: 'sqlAdminPassword=${{ secrets.AZURE_SQL_PASSWORD }} jwtSecretKey=${{ secrets.JWT_SECRET_KEY }} containerImageTag=${{ github.sha }} appGatewayCertificateData=${{ secrets.APP_GATEWAY_CERT_DATA }} appGatewayCertificatePassword=${{ secrets.APP_GATEWAY_CERT_PASSWORD }}'

      - name: Logout from Azure
        run: az logout
        if: always()